[functions]
  directory = "functions"

[functions.listMeta]
  included_files = ["index.html"]

[[redirects]]
  from = "/in/:evId/:slug"
  to = "/.netlify/functions/listMeta/:evId/:slug"
  status = 200
  force = true