[functions]
  directory = "functions/"
  # node_bundler = "esbuild"

[functions.listMeta]
  # included_files = ["functions/listMeta/listMeta.html"]

[functions.incf]
  included_files = ["functions/incf/test.json"]

[[redirects]]
  from = "/in/:evId/:slug"
  to = "/.netlify/functions/listMeta/:evId/:slug"
  status = 200
  force = true