[functions]
  directory = "functions/"

[functions.listMeta]
  included_files = ["./listMeta.html"]

[functions.incf]
  included_files = ["test.json"]

[[redirects]]
  from = "/in/:evId/:slug"
  to = "/.netlify/functions/listMeta/:evId/:slug"
  status = 200
  force = true